title: John Corney's Wild Ride
email: johncorneyswildride@gmail.com
description: >-
  Vítejte na oficiálních stránkách kapely John Corney’s Wild Ride. Naším úkolem
  je dobře hrát… a Vaším úkolem je dobře se bavit!
url: "https://johncorneyswildride.github.io/"
github_username:  johncorneyswildride
theme: tactile
